services:
  userfrontend:
    image: userfrontend
    build:
      context: .
      dockerfile: UserFrontend/Dockerfile

  userapi:
    image: userapi
    build:
      context: .
      dockerfile: Apis/UserApi/Dockerfile

